swagger: "2.0"
info:
  title: didi
  description: didi auto connect.
  version: 1.0.0
host: didi.m3m.dev
basePath: /api
schemes:
  - https

paths:
  /login:
    post:
      summary: login or create new user
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                deviceHash:
                  type: string
              example:
                username: mrm
                password: pass
                deviceHash: DEVICE_UNIQUE_HASH
      responses:
        '200':
          description: token and other data.
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  message:
                    type: string
                  link:
                    type: string
                  hasAccess:
                    type: boolean
                example:
                  token: a5c65213e46dd08bfaba2c75ff4eabaf
                  isLimit: false
                  link: "https://link-to-payment-page.cpm"
                  message: "مدت اعتبار حساب شما تمام شده است. لطفا اکانت خود را تمدید کنید"
        '400':
          description: wrong input.
        '401':
          description: wrong password.

  /hasAccess:
    get:
      summary: hasAccess
      parameters:
        - in: query
          name: deviceHash
          schema:
            type: string
          description: DEVICE_UNIQUE_HASH
      responses:
        '200':
          description: user.
          content:
            type: object
            properties:
              hashAccess:
                type: boolean
              message:
                type: string
            example:
              hashAccess: false
              message: "دستگاهی با این ایدی یافت نشد!"

        '400':
          description: wrong input.
        '401':
          description: wrong password.

  /isRegistered:
    get:
      summary: check if a username is registered
      parameters:
        - in: query
          name: username
          schema:
            type: string
          description: username of user
      responses:
        '200':
          description: user with this username is registered
        '400':
          description: wrong input.

  /didiAccount/get:
    get:
      summary: didi account get
      responses:
        '200':
          description: didi account.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  username:
                    type: string
                  password:
                    type: string
                  updatedAt:
                    type: integer
                  createdAt:
                    type: integer
                example:
                  id: 63df7815c8ce5c405561625e
                  username: 09991231212
                  password: pass
                  createdAt: 1675589653
                  updatedAt: 0

  /didiAccount/create:
    post:
      summary: didi account create
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              example:
                username: 09991231212
                password: pass

      responses:
        '200':
          description: account created.
        '409':
          description: account already exist.

  /didiAccount/delete/{id}:
    post:
      summary: didi account delete
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: id of didi account
      responses:
        '200':
          description: account created.
        '404':
          description: account didnt found.

  /didiAccount/modify/{id}:
    post:
      summary: didi account update
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: id of didi account

      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              example:
                username: 09991231212
                password: pass

      responses:
        '200':
          description: account created.
        '404':
          description: not found.
        '400':
          description: wrong input.
