swagger: "2.0"
info:
  title: didi
  description: didi auto connect.
  version: 1.0.0
host: didi.m3m.dev
basePath: /api
schemes:
  - https

paths:
  /login:
    post:
      summary: login or create new user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                deviceHash:
                  type: string
              example:
                username: mrm
                password: pass
                deviceHash: DEVICE_UNIQUE_HASH
      responses:
        '200':
          description: token and other data.
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  message:
                    type: string
                  link:
                    type: string
                  hasAccess:
                    type: boolean
                example:
                  token: a5c65213e46dd08bfaba2c75ff4eabaf
                  isLimit: false
                  link: "https://link-to-payment-page.cpm"
                  message: "مدت اعتبار حساب شما تمام شده است. لطفا اکانت خود را تمدید کنید"
        '400':
          description: wrong input.
        '401':
          description: wrong password.

  /hasAccess:
    get:
      summary: on each connect
      parameters:
        - in: query
          name: deviceHash
          schema:
            type: string
          description: DEVICE_UNIQUE_HASH
      responses:
        '200':
          description: user.
          content:
            type: object
            properties:
              hashAccess:
                type: boolean
              message:
                type: string
            example:
              hashAccess: false
              message: "دستگاهی با این ایدی یافت نشد!"

        '400':
          description: wrong input.
        '401':
          description: wrong password.